name: derivaty cron deploy 

on:
  schedule:
   - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{secrets.VERCEL_KEY}}
          now-args: '--prod'
          now-project-id: ${{secrets.PROJECT_ID}}
